services:
  generator:
    build: .
    image: strawberry-picker:blender-4.3.2
    platform: linux/amd64
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./dataset
        target: /app/dataset
      - type: bind
        source: ./scenes
        target: /output
